CREATE TABLE "devices" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"ip"	TEXT NOT NULL UNIQUE,
	"place"	TEXT NOT NULL UNIQUE,
	"description"	TEXT NOT NULL,
	"methodcheck"	TEXT NOT NULL DEFAULT 'ping' UNIQUE
);